apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: mern-app
data:
  MONGO_CONN_STR: "mongodb://mongodb-svc.mern-app.svc.cluster.local:27017/mern-todo?directConnection=true"
  USE_DB_AUTH: "true"
  PORT: "5000"
