apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: mern-app
  labels:
    app: backend
    env: dev
spec:
  selector:
    app: backend
    env: dev
  ports:
    - port: 5000
      targetPort: 5000
      name: http
  type: ClusterIP
