apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mongodb-pdb
  namespace: mern-app
  labels:
    app: mongodb
    env: dev
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: mongodb
      env: dev
