apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: mern-app
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: backend
      env: dev
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: mern-app
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: frontend
      env: dev
