apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-secret
  namespace: mern-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: mongodb-secret
    creationPolicy: Owner
  data:
    - secretKey: mongodb-username
      remoteRef:
        key: /mern-app/mongodb/username
    - secretKey: mongodb-password
      remoteRef:
        key: /mern-app/mongodb/password
