server {
  listen 80;
  server_name localhost;

  location = /healthz {
    add_header Content-Type text/plain;
    return 200 "OK";
  }

  location = /ready {
    add_header Content-Type text/plain;
    return 200 "OK";
  }

  location / {
    root /usr/share/nginx/html;
    try_files $uri $uri/ /index.html;
  }

  location = /favicon.ico {
    root /usr/share/nginx/html;
  }

  error_page 500 502 503 504 /50x.html;
  location = /50x.html {
    root /usr/share/nginx/html;
  }
}
